stellar-web/src/main/java/stellar/web/faces/HelloBean.java
package stellar.web.faces;

import javax.faces.bean.ManagedBean;

@ManagedBean(name="helloBean")
public class HelloBean {

    // Lombok
    private String name = "Brajanek";

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

stellar-web/src/main/java/stellar/web/faces/LocaleBean.java
package stellar.web.faces;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;

@ManagedBean
@SessionScoped
public class LocaleBean {

    private String language = FacesContext
            .getCurrentInstance()
            .getViewRoot()
            .getLocale()
            .getLanguage();

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
        FacesContext
                .getCurrentInstance()
                .getViewRoot()
                .setLocale(new Locale(language));
    }

    public List<Locale> getSupportedLocales(){
        Iterator<Locale> itr =
        FacesContext
                .getCurrentInstance()
                .getApplication()
                .getSupportedLocales();
        List<Locale> locales = new ArrayList<>();
        while (itr.hasNext()){
            locales.add(itr.next());
        }
        locales.add(
                FacesContext.getCurrentInstance()
                .getApplication()
                .getDefaultLocale()
        );
        return locales;
    }
}

stellar-web/src/main/java/stellar/web/faces/SearchBean.java
package stellar.web.faces;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;

@ManagedBean
public class SearchBean {

    private String phrase;

    private int systemId;

    @PostConstruct
    public void initSystemId(){
        String systemIdString =
                FacesContext.
                        getCurrentInstance().
                        getExternalContext().
                        getRequestParameterMap().
                        get("systemId");
        if(systemIdString!=null && !systemIdString.trim().isEmpty()){
            this.systemId = Integer.parseInt(systemIdString);
        }
    }

    public boolean isPhrasePresent(){
        return phrase!=null && !phrase.trim().isEmpty();
    }

    public String getPhrase() {
        return phrase;
    }

    public void setPhrase(String phrase) {
        this.phrase = phrase;
    }

    public int getSystemId() {
        return systemId;
    }

    public void setSystemId(int systemId) {
        this.systemId = systemId;
    }


}

stellar-web/src/main/java/stellar/web/faces/StellarBean.java
package stellar.web.faces;

import stellar.entities.Planet;
import stellar.entities.PlanetarySystem;
import stellar.service.api.StellarService;
import stellar.service.impl.StellarServiceImpl;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import java.util.List;

@ManagedBean
public class StellarBean {

    //@ManagedProperty("#{stellarService}")
    @Inject
    private StellarService service;

    @ManagedProperty("#{searchBean}")
    private SearchBean searchBean;




    public List<PlanetarySystem> getPlanetarySystems() {
        if (searchBean.isPhrasePresent()) {
            return service.getSystemsByName(searchBean.getPhrase());
        } else {
            return service.getSystems();
        }
    }

    public PlanetarySystem getPlanetarySystem(int systemId) {
        return service.getSystemById(systemId);
    }

    public List<Planet> getPlanets() {

        String systemIdString =
        FacesContext
                .getCurrentInstance()
                .getExternalContext()
                .getRequestParameterMap()
                .get("systemId");

        int systemId = Integer.parseInt(systemIdString);
        return service.getPlanets(service.getSystemById(systemId));

    }

    public StellarService getService() {
        return service;
    }

    public void setService(StellarService service) {
        this.service = service;
    }


    public SearchBean getSearchBean() {
        return searchBean;
    }

    public void setSearchBean(SearchBean searchBean) {
        this.searchBean = searchBean;
    }
}

stellar-web/src/main/java/stellar/web/servlet/HelloServlet.java
package stellar.web.servlet;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.logging.Logger;

public class HelloServlet extends HttpServlet {

    private Logger logger = Logger.getLogger(HelloServlet.class.getName());

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        logger.info("welcoming user");

        resp.getWriter().write("<html><body>Hey Joe!</body></html>");
    }
}

stellar-web/src/main/java/stellar/web/servlet/PlanetsServlet.java
package stellar.web.servlet;

import stellar.entities.Planet;
import stellar.service.api.StellarService;
import stellar.service.impl.StellarServiceImpl;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.security.Principal;
import java.util.List;
import java.util.logging.Logger;

public class PlanetsServlet extends HttpServlet {

    Logger logger = Logger.getLogger(PlanetsServlet.class.getName());

    @Inject
    StellarService service;
    // fake comment
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String systemIdString = req.getParameter("systemId");
        try {
            int systemId = Integer.parseInt(systemIdString);
            logger.info("about to fetch planets of system " + systemId);

            Principal principal = req.getUserPrincipal();
            String principalName = principal.getName();
            boolean vip = req.isUserInRole("VIP");
            logger.info("principal. name: " + principalName + ", vip:" + vip);

            List<Planet> planets = service.getPlanets( service.getSystemById(systemId) );
            req.setAttribute("planets", planets);

            req.getRequestDispatcher("/WEB-INF/jsp/planets.jsp").forward(req, resp);

        }catch (NumberFormatException e){
            throw new IllegalArgumentException("system id invalid", e);
        }
    }
}

stellar-web/src/main/java/stellar/web/servlet/SystemsServlet.java
package stellar.web.servlet;

import stellar.entities.PlanetarySystem;
import stellar.service.api.StellarService;
import stellar.service.impl.StellarServiceImpl;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;
import java.util.logging.Logger;

public class SystemsServlet extends HttpServlet {

    private Logger logger = Logger.getLogger(SystemsServlet.class.getName());

    @Inject
    private StellarService service;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        logger.info("about to fetch planetary systems");

        List<PlanetarySystem> systems = service.getSystems();
        forward(req, resp, systems);

    }

    private void forward(HttpServletRequest req, HttpServletResponse resp, List<PlanetarySystem> systems) throws ServletException, IOException {
        req.setAttribute("systems", systems);
        req.getRequestDispatcher("/WEB-INF/jsp/systems.jsp").forward(req, resp);
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String phrase = req.getParameter("phrase");
        List<PlanetarySystem> systems = service.getSystemsByName(phrase);
        forward(req, resp, systems);
    }
}

stellar-web/src/main/webapp/WEB-INF/jsp/footer.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>


    </section>
</article>
<footer>
    <span>JSP</span>
</footer>

</body>
</html>

stellar-web/src/main/webapp/WEB-INF/jsp/header.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<html>
<head>
    <title>Planetary Systems</title>
    <link rel="stylesheet" href="<c:url value="/resources/css/style.css"/>"/>
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
</head>
<body>

<header>
    <nav>
        <ul>
            <li class="active"><a
                    href="./systems">Stellar Catalogue</a></li>
        </ul>
        <span>${pageContext.request.userPrincipal.name}</span>
    </nav>
</header>

<article>
    <jsp:include page="search.jsp"/>
    <section class="data">

stellar-web/src/main/webapp/WEB-INF/jsp/planets.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<jsp:include page="header.jsp"/>

<table>
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
    </tr>
    </thead>

    <tbody>
    <c:forEach items="${requestScope.planets}" var="p">
        <tr>
            <td>${p.id}</td>
            <td>${p.name}</td>
        </tr>
    </c:forEach>
    </tbody>


</table>


<jsp:include page="footer.jsp"/>

stellar-web/src/main/webapp/WEB-INF/jsp/search.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<div id="search">
    <span>SEARCH</span>
    <form method="post" action="./systems" class="search-container" enctype="application/x-www-form-urlencoded">
        <input name="phrase" type="text"><input type="submit" value="">
    </form>
</div>

stellar-web/src/main/webapp/WEB-INF/jsp/systems.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<jsp:include page="header.jsp"/>

<span>Planetary Systems</span>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Star</th>
            <th>Distance</th>
        </tr>
    </thead>

    <tbody>

        <c:forEach items="${requestScope.systems}" var="s">
        <tr>
            <td><a href="./planets?systemId=${s.id}">${s.name}</a></td>
            <td>${s.star}</td>
            <td>${s.distance}</td>
        </tr>
        </c:forEach>


    </tbody>
</table>

<jsp:include page="footer.jsp"/>

stellar-web/src/main/webapp/jsf/addSystems.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
>

<h:body>


        <ui:composition template="template.xhtml">
            <ui:param name="displaySearch" value="false"/>
            <ui:define name="title">
                #{msg['label.planetary.system.add.title']}
            </ui:define>
            <ui:define name="content">

                <h:form>
                    <h:outputLabel>#{msg['label.planetary.system.name']}</h:outputLabel>
                    <h:inputText required="true" value="#{planetarySystemForm.name}"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.star']}</h:outputLabel>
                    <h:inputText id="star" required="true"  maxlength="10" value="#{planetarySystemForm.star}">
                        <f:validateLength minimum="2" maximum="10"/>
                    </h:inputText>
                    <h:message for="star" style="color: red"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.distance']}</h:outputLabel>
                    <h:inputText id="distance" value="#{planetarySystemForm.distance}">
                        <f:validateDoubleRange minimum="0"/>
                    </h:inputText>
                    <h:message for="distance" style="color: red"/>
                    <br/>
                    <h:outputLabel >#{msg['label.planetary.system.discovery']}</h:outputLabel>
                    <h:inputText id="discovery" value="#{planetarySystemForm.discovery}">
                        <f:convertDateTime type="date" pattern="yyyy-MM-dd"/>
                    </h:inputText>
                    <h:message for="discovery" style="color: red;"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.details']}</h:outputLabel>
                    <h:inputText id="details" value="#{planetarySystemForm.details}">
                        <f:converter converterId="urlConverter"/>
                    </h:inputText>
                    <h:message for="details" style="color: red;"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.next']}</h:outputLabel>
                    <h:selectBooleanCheckbox value="#{planetarySystemForm.next}"/>
                    <br/>
                    <h:commandButton
                            action="#{planetarySystemForm.add}"
                            value="${msg['label.planetary.system.add.button']}"/>
                </h:form>

            </ui:define>

        </ui:composition>

</h:body>

</html>

stellar-web/src/main/webapp/jsf/hello.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <h:outputLabel value="Hello, #{helloBean.name}"/>
</f:view>
</html>

stellar-web/src/main/webapp/jsf/planets.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition template="template.xhtml">
    <ui:define name="title">Planets</ui:define>
    <ui:define name="content">

        <h:dataTable value="#{stellarBean.planets}" var="p">
            <h:column>
                <f:facet name="header">ID</f:facet>
                #{p.id}
            </h:column>
            <h:column>
                <f:facet name="header">Name</f:facet>
                #{p.name}
            </h:column>
        </h:dataTable>

    </ui:define>
</ui:composition>

</html>

stellar-web/src/main/webapp/jsf/search.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
>
<f:view>
    <div id="search">
        <span>SEARCH</span>
        <h:form styleClass="search-container" >
            <h:inputText value="#{searchBean.phrase}"/>
            <h:commandButton/>
        </h:form>
    </div>
</f:view>
</html>

stellar-web/src/main/webapp/jsf/systems.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


<ui:composition template="template.xhtml">

    <ui:param name="displaySearch" value="true"></ui:param>
    <ui:define name="title">Prlanetary Systems</ui:define>
    <ui:define name="content">

     <h:dataTable var="s" value="#{stellarBean.planetarySystems}">
        <h:column>
            <f:facet name="header">#{msg["system.name"]}</f:facet>
            <h:link value="#{s.name}" outcome="planets">
                <f:param name="systemId" value="#{s.id}"/>
            </h:link>
        </h:column>
        <h:column>
             <f:facet name="header">#{msg["system.star"]}</f:facet>
             #{s.star}
        </h:column>
         <h:column>
             <f:facet name="header">#{msg["system.distance"]}</f:facet>
             #{s.distance}
         </h:column>
         <h:column>
             <f:facet name="header">#{msg["system.discovery"]}</f:facet>
             #{s.discovery}
         </h:column>
     </h:dataTable>
    </ui:define>

</ui:composition>

</html>

stellar-web/src/main/webapp/jsf/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
>

<h:head>
    <title>Stellar</title>
    <h:outputStylesheet library="css" name="style-jsf.css"/>
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet"/>
</h:head>
<h:body>

    <header>
        <nav>
            <ul>
                <li class="active"><a
                        href="./systems.faces">Stellar Catalogue</a></li>
            </ul>
            <span>
                <h:form>
                    <h:selectOneMenu value="#{localeBean.language}"
                    onchange="submit()">
                        <f:selectItems
                                value="#{localeBean.supportedLocales}"
                                var="loc"
                                itemLabel="#{loc.getDisplayLanguage(loc)}"
                            />
                    </h:selectOneMenu>
                </h:form>
            </span>
        </nav>
    </header>

    <article>

        <c:if test="#{displaySearch}">
            <ui:include src="search.xhtml"/>
        </c:if>

        <section class="data">
            <span><ui:insert name="title">TODO</ui:insert></span>

            <ui:insert name="content"/>

        </section>
    </article>

    <footer>
        <span>JSF</span>
    </footer>



</h:body>

</html>